### ISSUE TITLE
Switch to Koa

### ISSUE THREAD

**Issue by st0ffern** [jkettmann/universal-react-relay-starter-kit#54]
Koa is just alot better

**Comment by jkettmann** [comment]
Thanks for your interest. Can you elaborate a bit more? I don't have experience with Koa and not so much time right now to rewrite the server. But contributions are welcome.

**Comment by st0ffern** [comment]
I have created a server system here: https://github.com/stoffern/universal-app
With ability to add a universal app, and then later add passport, graphql, and relay if needed with simple commmands. 😉
