### ISSUE TITLE
Mutation error handling

### ISSUE THREAD

**Issue by jkettmann** [jkettmann/universal-react-relay-starter-kit#68]
- [x] Login
- [x] Register
- [x] Verify

**Comment by jkettmann** [comment]
Wait for [relay-compose issue](https://github.com/ErrorPro/relay-compose/issues/3) to be resolved

**Comment by MartinDawson** [comment]
Can't you just reject the error like [here](https://github.com/MartinDawson/SoundVast/blob/graphql/src/SoundVast/wwwroot/components/app/environment/environment.js#L22)

And then handle the errors in the [catch](https://github.com/MartinDawson/SoundVast/blob/graphql/src/SoundVast/wwwroot/components/account/login/loginContainer.js#L11)?

**Comment by jkettmann** [comment]
That works, but feels like a workaround. I like the approach of [relay-commit-mutation-promise](https://github.com/robrichard/relay-commit-mutation-promise/blob/master/index.js) better, where they reject the promise in `onComplete`. Anyways I think there's a bug in relay-compose, since there the errors just get swallowed. There might be a nicer solution, when that issue is fixed.

But for now, it's a good way to make it work.

**Comment by jkettmann** [comment]
@MartinDawson There also seems to be a problem in your code, since catch looks like following:

```
..Mutation(input).catch((error) => {
      throw new SubmissionError(error);
}),
```

`error` might be an array of errors thrown in the fetcher or a single error from the `onError` callback in `createMutation`, right?
