### ISSUE TITLE
Server entrypoint

### ISSUE THREAD

**Issue by ermik** [jkettmann/universal-react-relay-starter-kit#95]
how does `main.js` get created?
https://github.com/jkettmann/universal-react-relay-starter-kit/blob/3c70b1a19beda6baf85bcfcc089fa6990b328108/server/render/index.js#L65

**Comment by jkettmann** [comment]
`main.js` is created by webpack. See this [config file](https://github.com/jkettmann/universal-react-relay-starter-kit/blob/3c70b1a19beda6baf85bcfcc089fa6990b328108/webpack/server.prod.js#L10). This config is used during the [build:client](https://github.com/jkettmann/universal-react-relay-starter-kit/blob/master/package.json#L28) command

**Comment by ermik** [comment]
Yeah, I've spent some time making the similar scenario happen and ended up looping the server on Get request — there is a circular import somewhere when using webpack-made client.
